center_of_gravity: [-0.00043172653363333046, -0.0004343891316282389, -0.04700985542941953]
gravity_vector: [0.0, 0.0, -9.80665]
origin_frame: base_link
target_frame: wrist_ft_sensor_frame
weight: 0.5831271326715917
